---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webapp
  labels:
    name: webapp-deployment
    app: webapp

spec:
  replicas: 5
  selector:
    matchLabels:
      name: webapp-pod
      app: webapp
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      name: webapp-pod
      labels:
        name: webapp-pod
        app: webapp
    spec:
      containers:
        - name: webapp
          image: blackpearl001/webapp:v1.2
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
...
